version: '3'
services:
  sandbox:
    image: ghcr.io/imolcean/gnucash-vnc:main
    container_name: gnucash-vnc
    restart: unless-stopped
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gnucash-vnc/config:/config
    ports:
      - 6080:3000
    environment:
      - PUID=100
      - PGID=1000
      - TZ=Europe/Berlin
